# Generated by Django 5.0.3 on 2024-03-31 17:42

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default=None, max_length=44, null=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(default=None, max_length=250, null=True)),
                ('password', models.CharField(default=None, max_length=228, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('supermanager', 'Supermanager'), ('operator', 'Operator')], max_length=12)),
                ('account_type', models.CharField(choices=[('manager', 'Manager'), ('customer', 'Customer')], default='customer', max_length=8)),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('query', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(default=None, max_length=34, null=True)),
                ('last_name', models.CharField(default=None, max_length=34, null=True)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='unique_user_username'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_user_email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('account_type__in', ['manager', 'customer'])), name='check_account_type_valid_choices'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['supermanager', 'operator'])), name='check_user_role_valid_choices'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='cliver.user'),
        ),
    ]
